name: flutter_midi_command_linux
description: FlutterMidiCommand for Linux.
version: 1.0.0
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand
repository: https://github.com/InvisibleWrench/FlutterMidiCommand/tree/main/packages/flutter_midi_command_linux
issue_tracker: https://github.com/InvisibleWrench/FlutterMidiCommand/issues
documentation: https://github.com/InvisibleWrench/FlutterMidiCommand/tree/main/packages/flutter_midi_command_linux
topics:
  - midi
  - flutter-plugin
  - linux
  - alsa
  - serial

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command_platform_interface: ^1.0.0
  midi: ^0.1.0
  ffi: ^2.0.1
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_midi_command
    platforms:
      linux:
        dartPluginClass: FlutterMidiCommandLinux
