name: flutter_midi_command
description: A Flutter plugin for sending and receiving MIDI messages between Flutter and physical and virtual MIDI devices.
publish_to: none

version: 1.0.0
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.12.0
  flutter_midi_command_platform_interface:
    path: packages/flutter_midi_command_platform_interface
  flutter_midi_command_linux:
    path: packages/flutter_midi_command_linux
  flutter_midi_command_windows:
    path: packages/flutter_midi_command_windows
  flutter_midi_command_web:
    path: packages/flutter_midi_command_web
  flutter_midi_command_android:
    path: packages/flutter_midi_command_android
  flutter_midi_command_darwin:
    path: packages/flutter_midi_command_darwin
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  melos: ^6.3.2
  pigeon: ^22.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        default_package: flutter_midi_command_android
      ios:
        default_package: flutter_midi_command_darwin
      macos:
        default_package: flutter_midi_command_darwin
      linux:
        default_package: flutter_midi_command_linux
      windows:
        default_package: flutter_midi_command_windows
      web:
        default_package: flutter_midi_command_web
