name: flutter_midi_command_darwin
description: Darwin (iOS/macOS) serial MIDI wrapper for flutter_midi_command.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command_platform_interface:
    path: ../flutter_midi_command_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_midi_command
    platforms:
      ios:
        pluginClass: FlutterMidiCommandPlugin
      macos:
        pluginClass: SwiftFlutterMidiCommandPlugin
