name: flutter_midi_command_web
description: Web MIDI browser implementation for flutter_midi_command.
version: 1.0.0
homepage: https://github.com/InvisibleWrench/FlutterMidiCommand
repository: https://github.com/InvisibleWrench/FlutterMidiCommand/tree/main/packages/flutter_midi_command_web
issue_tracker: https://github.com/InvisibleWrench/FlutterMidiCommand/issues
documentation: https://github.com/InvisibleWrench/FlutterMidiCommand/tree/main/packages/flutter_midi_command_web
topics:
  - midi
  - flutter-plugin
  - webmidi
  - browser
  - web

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  flutter_midi_command_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_midi_command
    platforms:
      web:
        pluginClass: FlutterMidiCommandWeb
        fileName: flutter_midi_command_web.dart
